HOST: "0.0.0.0"
HOSTNAME: "myc-devices-simulator-api.localhost"
PORT: 1325
BASEURL: "http://myc-devices-simulator-api.localhost"
SERVERURI: "https://localhost:1325"
DBPOSTGRES: "postgres://postgres:postgres@localhost:5430/postgres?sslmode=disable"
DBMAXIDLECONNS: "1"
DBMAXOPENCONNS: "0"
DBLOGGER: "false"
ENVIRONMENT: "local"
POSTMARKTOKEN: "fakeMailerToken"
SMTPHOST: "localhost"
SMTPPORT: "25"
SMTPNETWORK: "tcp"
SMTPFROM: "no-reply@mycircutor.com"