// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	db "myc-devices-simulator/business/db"

	mock "github.com/stretchr/testify/mock"

	sql "database/sql"
)

// SQLGbc is an autogenerated mock type for the SQLGbc type
type SQLGbc struct {
	mock.Mock
}

// Commit provides a mock function with given fields:
func (_m *SQLGbc) Commit() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exec provides a mock function with given fields: query, args
func (_m *SQLGbc) Exec(query string, args ...interface{}) (sql.Result, error) {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 sql.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(string, ...interface{}) (sql.Result, error)); ok {
		return rf(query, args...)
	}
	if rf, ok := ret.Get(0).(func(string, ...interface{}) sql.Result); ok {
		r0 = rf(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(string, ...interface{}) error); ok {
		r1 = rf(query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Prepare provides a mock function with given fields: query
func (_m *SQLGbc) Prepare(query string) (*sql.Stmt, error) {
	ret := _m.Called(query)

	var r0 *sql.Stmt
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*sql.Stmt, error)); ok {
		return rf(query)
	}
	if rf, ok := ret.Get(0).(func(string) *sql.Stmt); ok {
		r0 = rf(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Stmt)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Rollback provides a mock function with given fields:
func (_m *SQLGbc) Rollback() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TxBegin provides a mock function with given fields:
func (_m *SQLGbc) TxBegin() (db.SQLGbc, error) {
	ret := _m.Called()

	var r0 db.SQLGbc
	var r1 error
	if rf, ok := ret.Get(0).(func() (db.SQLGbc, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() db.SQLGbc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(db.SQLGbc)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TxEnd provides a mock function with given fields: txFunc
func (_m *SQLGbc) TxEnd(txFunc func() error) error {
	ret := _m.Called(txFunc)

	var r0 error
	if rf, ok := ret.Get(0).(func(func() error) error); ok {
		r0 = rf(txFunc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewSQLGbc interface {
	mock.TestingT
	Cleanup(func())
}

// NewSQLGbc creates a new instance of SQLGbc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSQLGbc(t mockConstructorTestingTNewSQLGbc) *SQLGbc {
	mock := &SQLGbc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
