kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 2323
        hostPort: 2323
      - containerPort: 5432
        hostPort: 5432
      - containerPort: 80
        hostPort: 80
        protocol: TCP